### ISSUE TITLE
Fix: Use CSS to hide headings from visual presentation 

### ISSUE THREAD

**Issue by neilmispelaar** [imd1005-web-development-winter-2023/assignment-02-Krowno04#3]
Hi @Krowno04 

Please us CSS to hide headings and other content from visual users. 

The `hidden` attribute takes the content and completely pulls it from the document, so screen readers won't actually be able to hear it at all. 

From one of the exercises. You don't have to use the following class, there are other ways to implement CSS for "screen reader only" text. 

```css
.sr-only {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    white-space: nowrap;
    border-width: 0;
}
```

https://github.com/imd1005-web-development-winter-2023/assignment-02-Krowno04/blob/96cbb9291676631c028517227d1f6ced2b841991/index.html#L17
